import { Link } from 'react-router-dom'
import { AlertTriangle, ArrowRight, BadgeCheck, Building2, FileCheck2, FileText, Headset, LockKeyhole, MapPin, PhoneCall, SearchCheck, ShieldAlert, ShieldCheck } from 'lucide-react'
import { contactDetails, financingHighlights, guideCards, processSteps, products } from '../data'
import { ButtonLink, Checklist, CTASection, PageHero, SafeNote, SectionHead } from '../components/UI'

export function Financing() {
  return <>
    <PageHero eyebrow="Pilihan pembiayaan" title="Pembiayaan untuk warga sektor awam" text="Bandingkan dua produk aktif dan fahami skop pembiayaan sebelum mendapatkan semakan berdasarkan profil anda.">
      <ButtonLink to="/semak-kelayakan">Semak Kelayakan Saya</ButtonLink>
    </PageHero>
    <section className="section"><div className="container product-grid">{products.map(p => { const Icon = p.icon; return <article className={`product-panel ${p.tone}`} key={p.slug}><div className="product-icon"><Icon /></div><span>{p.eyebrow}</span><h2>{p.name}</h2><p>{p.summary}</p><Link to={`/produk/${p.slug}`}>Lihat butiran produk <ArrowRight size={16} /></Link></article> })}</div></section>
    <section className="section soft-section"><div className="container">
      <SectionHead eyebrow="Ciri & pertimbangan" title="Lihat gambaran penuh sebelum memilih" text="Maklumat berikut ialah panduan indikatif berdasarkan program yang dipasarkan melalui CoshareEZ. Butiran sebenar perlu disahkan mengikut produk, profil pemohon dan terma semasa." align="center" />
      <div className="benefit-grid">{financingHighlights.map(({ icon: Icon, label, title, text }) => <article className="benefit-card" key={title}><Icon /><span>{label}</span><h3>{title}</h3><p>{text}</p></article>)}</div>
      <SafeNote>Julat jumlah dan tempoh bukan tawaran atau jaminan kelulusan. Pegawai akan mengesahkan maklumat produk semasa sebelum dokumen lengkap diminta.</SafeNote>
    </div></section>
    <section className="section"><div className="container two-col-content"><div><SectionHead eyebrow="Perbandingan yang bertanggungjawab" title="Produk yang sesuai bergantung pada profil, bukan label popular" text="Pegawai akan menilai kategori majikan, status pekerjaan, pendapatan, komitmen dan dokumen sebelum menerangkan pilihan yang mungkin berkaitan." /></div><Checklist items={['Dua produk aktif sahaja', 'Terma dirujuk kepada maklumat semasa', 'Tiada produk dipilih secara automatik', 'Keputusan akhir oleh pihak pembiaya']} /></div></section>
    <CTASection />
  </>
}

export function ProcessPage() { return <><PageHero eyebrow="Cara memohon" title="Ketahui apa yang berlaku pada setiap langkah" text="Proses yang jelas membantu anda menyediakan maklumat tepat tanpa berkongsi dokumen terlalu awal."><ButtonLink to="/semak-kelayakan">Mulakan Semakan Awal</ButtonLink></PageHero><section className="section"><div className="container process-list">{processSteps.map(({ icon: Icon, title, text }, i) => <div key={title}><span>0{i + 1}</span><Icon /><div><h2>{title}</h2><p>{text}</p></div></div>)}</div></section><CTASection /></> }

export function DocumentsPage() { return <><PageHero eyebrow="Kelayakan & dokumen" title="Sediakan perkara yang betul pada waktu yang betul" text="Semakan awal menggunakan maklumat asas. Dokumen sensitif hanya diminta apabila pilihan berkaitan telah dikenal pasti."><ButtonLink to="/semak-kelayakan">Semak Kelayakan</ButtonLink></PageHero><section className="section"><div className="container two-col-content"><div><SectionHead eyebrow="Kelayakan asas" title="Siapa yang boleh membuat semakan?" /><Checklist items={['Kakitangan kerajaan Persekutuan atau Negeri', 'Kakitangan badan berkanun dan PBT', 'Kakitangan GLC yang berada dalam kategori terpilih', 'Status dan tempoh pekerjaan tertakluk pada produk']} /></div><div className="document-stack"><div><FileText /><span>Kad pengenalan</span></div><div><FileCheck2 /><span>Slip gaji terkini</span></div><div><Building2 /><span>Pengesahan pekerjaan</span></div><p>Senarai tepat boleh berbeza mengikut produk. Jangan hantar dokumen sebelum menerima arahan melalui saluran rasmi.</p></div></div></section><CTASection /></> }

export function Guides() { return <><PageHero eyebrow="Pusat panduan" title="Maklumat yang membantu anda bertanya soalan yang betul" text="Panduan ringkas untuk memahami kelayakan, dokumen, proses dan keselamatan pembiayaan." /><section className="section"><div className="container guide-grid">{guideCards.map(({ icon: Icon, title, text }) => <article key={title}><Icon /><h2>{title}</h2><p>{text}</p><span className="coming-label">Artikel sedang disediakan</span></article>)}</div></section></> }

export function About() { return <><PageHero eyebrow="Mengenai kami" title="Bantuan yang jelas, melalui saluran yang boleh disahkan" text="CoshareEZ ialah agensi pemasaran sah bagi produk Coshare dan memberi fokus kepada proses permohonan warga sektor awam." aside={<div className="product-mark navy"><BadgeCheck /><span>Fokus kami</span><strong>Jelas · Teratur · Selamat</strong></div>} /><section className="section"><div className="container two-col-content"><div><SectionHead eyebrow="Peranan CoshareEZ" title="Kami membantu proses. Pihak pembiaya membuat keputusan." text="Pegawai membantu semakan awal, menerangkan dokumen dan menguruskan langkah permohonan. Kami tidak menjanjikan kelulusan atau meminta bayaran pendahuluan." /></div><div className="principles-list"><div><span>01</span><h3>Maklumat yang mudah difahami</h3></div><div><span>02</span><h3>Perlindungan data sejak awal</h3></div><div><span>03</span><h3>Urusan melalui identiti rasmi</h3></div></div></div></section><section className="section soft-section"><div className="container partnership-panel"><div><span className="eyebrow">Kerjasama organisasi</span><h2>Saluran penerangan untuk kumpulan kakitangan</h2><p>CoshareEZ terbuka kepada program penerangan yang terancang bersama GLC, syarikat tersenarai, badan berkanun dan organisasi terpilih. Skop kelayakan, bahan komunikasi dan proses rujukan disahkan sebelum program dimulakan.</p></div><ButtonLink to="/hubungi" secondary>Bincang kerjasama</ButtonLink></div></section></> }

export function Safety() { return <><PageHero eyebrow="Keselamatan" title="Kenal pasti saluran yang betul sebelum berkongsi dokumen" text="Berhenti dan semak jika seseorang meminta wang pendahuluan, akaun peribadi atau menjanjikan kelulusan tanpa penilaian." aside={<div className="privacy-bubble danger"><ShieldAlert /><strong>Jangan buat bayaran awal</strong><span>Semak pegawai dan saluran terlebih dahulu.</span></div>} /><section className="section"><div className="container risk-grid"><div className="risk-card bad"><AlertTriangle /><h2>Tanda amaran</h2><Checklist items={['Meminta bayaran ke akaun peribadi', 'Menjanjikan kelulusan 100%', 'Mendesak penghantaran IC tanpa penerangan', 'Menggunakan nombor yang tidak dapat disahkan']} /></div><div className="risk-card good"><ShieldCheck /><h2>Amalan CoshareEZ</h2><Checklist items={['Tiada bayaran pendahuluan', 'Tujuan dokumen diterangkan', 'Pegawai boleh disahkan', 'Keputusan tertakluk pada pihak pembiaya']} /></div></div></section></> }

export function VerifyOfficer() { return <><PageHero eyebrow="Pengesahan pegawai" title="Pastikan siapa yang menghubungi anda" text="Gunakan nombor telefon atau ID pegawai untuk membuat semakan sebelum menghantar dokumen." /><section className="section"><div className="container verify-shell"><SearchCheck /><h2>Semakan direktori pegawai</h2><p>Direktori sebenar perlu disambungkan kepada pangkalan data pegawai yang diluluskan sebelum pelancaran.</p><div className="verify-input"><input aria-label="Nombor telefon atau ID pegawai" placeholder="Masukkan nombor telefon atau ID pegawai" /><button className="button button-primary" onClick={() => alert('Direktori pegawai belum disambungkan dalam prototaip ini.')}>Semak Pegawai</button></div><SafeNote>Jika ragu-ragu, hubungi talian rasmi 017 447 4404.</SafeNote></div></section></> }

export function Contact() { return <><PageHero eyebrow="Hubungi kami" title="Bercakap melalui saluran rasmi CoshareEZ" text="Dapatkan penjelasan tentang semakan pembiayaan, status permohonan atau peluang ejen." /><section className="section"><div className="container contact-grid">{contactDetails.map(({ icon: Icon, label, value, href }) => { const content = <><Icon /><span>{label}</span><strong>{value}</strong></>; return href ? <Link key={label} to={href}>{content}</Link> : <div key={label}>{content}</div> })}</div><div className="container address-panel"><MapPin /><div><h2>Pejabat Kota Damansara</h2><p>No 25-G, Jalan PJU 5/20A, Pusat Perdagangan The Strand, Kota Damansara, 47810 Petaling Jaya, Selangor.</p></div><a className="button button-secondary" href="tel:+60174474404"><PhoneCall size={17} /> Hubungi Pejabat</a></div></section></> }

export function StatusPage() { return <><PageHero eyebrow="Pelanggan sedia ada" title="Semak status permohonan" text="Gunakan nombor rujukan yang diberikan oleh pegawai. Jangan masukkan nombor IC penuh pada halaman ini." /><section className="section"><div className="container verify-shell"><Headset /><h2>Masukkan nombor rujukan</h2><div className="verify-input"><input aria-label="Nombor rujukan" placeholder="Contoh: CEZ-000000" /><button className="button button-primary" onClick={() => alert('Sistem status belum disambungkan dalam prototaip ini.')}>Semak Status</button></div><SafeNote>Untuk bantuan, hubungi 017 447 4404 melalui saluran rasmi.</SafeNote></div></section></> }

export function LegalPage({ type = 'privacy' }) { const privacy = type === 'privacy'; return <><PageHero eyebrow="Maklumat undang-undang" title={privacy ? 'Notis Privasi' : 'Terma & Syarat'} text={privacy ? 'Ketahui bagaimana data peribadi dikumpul, digunakan, dikongsi dan dilindungi.' : 'Terma penggunaan laman dan proses semakan CoshareEZ.'} /><section className="section"><div className="container legal-copy"><LockKeyhole /><h2>{privacy ? 'Notis penuh perlu disahkan sebelum pelancaran' : 'Terma penuh perlu disahkan sebelum pelancaran'}</h2><p>Halaman prototaip ini menyediakan lokasi dan struktur sahaja. Kandungan undang-undang akhir perlu disemak oleh pemilik data dan penasihat pematuhan dalam Bahasa Melayu serta Bahasa Inggeris.</p></div></section></> }
